---
title: "Binary Classification Final Algorithm"
author: "Leyuan Qian"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Preprocessing

```{r}
training_data<-read.table("training_data.txt",header=T) # Load training data
testing_data<-read.table("test_data.txt",header=T) # Load test data

# Re-categorize the training data
training_set=training_data
training_set$binary_activity[which(training_set$activity<=3)]="dynamic"
training_set$binary_activity[which(training_set$activity>=4)]="static"
training_set$binary_activity=as.factor(training_set$binary_activity)
training_set=training_set[,c(-1,-2)]
```

## Split Training Data for Hold-out Validation 

```{r}
set.seed(123)
n_subjects=nrow(training_set)
split_7_3 = sample(1:n_subjects,n_subjects*0.7)
train = training_set[split_7_3,]
test = training_set[-split_7_3,]
```

## Use glm for classification

```{r}
glm.fit=glm(binary_activity ~ ., data=train,family=binomial,maxit=200)
glm.probs=predict(glm.fit, test, type="response")
glm.pred=rep("dynamic",dim(test)[1])
glm.pred[glm.probs>0.5] = "static"

# model evaluation
mean(glm.pred==test$binary_activity) # accuracy
glm.pred2=rep(1,dim(test)[1])
glm.pred2[glm.probs>=0.5] = 0
glm2=rep(1,dim(test)[1])
glm2[test$binary_activity=="static"]=0
roc(glm2,glm.pred2) # auc
```

## Predict the binary activity for the test data

```{r}
final_probs=predict(best.fit, testing_data, type="response")
final_pred=rep("dynamic",dim(testing_data)[1])
final_pred[final_probs>0.5] = "static"
final_pred2=rep(1,dim(testing_data)[1])
final_pred2[final_probs>=0.5] = 0
final=as.matrix(final_pred2,ncol=1) # Binary classification result

#write.table(final,"binary_ctest.txt", row.names = F, col.names = F)
```

